### PR TITLE
Homepage UI responsiveness

### LINKED ISSUE #18: [Bug]: Need to improve the responsiveness on home page for text
### Contact Details

latishadwani705@gmail.com

### What happened?

https://github.com/AppointNext/AppointNext/assets/104522651/2db1563b-149a-4349-a13a-12ad4ebafa12

Now in this video we can see that the size of text is not increasing and decreasing with change in the size of screen 
we need to improve this to improve ux 

### What browsers are you seeing the problem on?

Chrome

### Relevant log output

_No response_

### Are you interested in contributing?

- [ ] I'd like to work on this issue

### Code of Conduct

- [X] I have used the search function to check if an issue already exists
- [X] I agree to follow this project's Code of Conduct

### Which program are you contributing in?

Not applicable

### PR DESCRIPTION
**Pull request by Mehak-Mattoo**
## Pull Request Details
Made the whole homepage UI responsive

### Description

1. Used tailwind to responsiveness
2. Made the website content relative to website function
3. Added margin in testimonial section
4. Increased text size of navbar and footer on large screens

### Fixes

 issue  closes #18 and #17

### Type of PR
 [ ] Feature enhancement

### Summary
1. Used tailwind to responsiveness
2. Made the website content relative to website function
3. Added margin in testimonial section

### Screenshots (if applicable)

a1
a2
a3

### Additional Notes

email associated- mehakmattoo7@gmail.com

### Checklist

- [ ] I have read and followed the [Pull Requests and Issues guidelines](https://github.com/digitomize/digitomize/blob/main/PR_GUIDELINES.md#pull-requests-and-issues).
- [ ] The code has been properly linted and formatted using `npm run lint:fix` and `npm run format:fix`.
- [ ] I have tested the changes thoroughly before submitting this pull request.
- [ ] I have provided relevant issue numbers, snapshots, and videos after making the changes.
- [ ] I have not borrowed code without disclosing it, if applicable.
- [ ] This pull request is not a Work In Progress (WIP), and only completed and tested changes are included.
- [ ] I have tested these changes locally.
- [ ] My code follows the project's style guidelines.
- [ ] I have updated the documentation accordingly.
- [ ] This PR has a corresponding issue in the issue tracker.

## Summary by CodeRabbit

- **New Features**
  - Added new sections and updated text content in `Feature` and `Footer` components.

- **Style**
  - Improved layout and visual styling across `Feature`, `FeedBox`, `Feedback`, `Footer`, `Hero`, `Navbar`, and `SubscribeLetter` components, including updates to classes, font sizes, and colors.

- **Bug Fixes**
  - Adjusted `Navbar` button functionalities and text content for better user experience.

### CODE REVIEW

**Review by Latish705 — APPROVED** [review]
Show a video what changes you have made

**Comment by Mehak-Mattoo** [comment]
Sure, here it is
https://github.com/AppointNext/AppointNext/assets/77096365/94c1059e-1b23-42d5-ba43-144cb4736204

**Comment by Latish705** [comment]
@Mehak-Mattoo done great work but there you have removed image from home page
--- 
image

**Comment by Latish705** [comment]
@Mehak-Mattoo need to restructure the previous layout look good 

image

previously
image


main the text and layout not look good

**Comment by Mehak-Mattoo** [comment]
Done, changed the layout to your liking

**Comment by Latish705** [comment]
@Mehak-Mattoo I see some text not proper for mobile 
image
heading text look little big for mobile devices
and we can let It the image you hidden to seen on small devices

**Comment by Mehak-Mattoo** [comment]
Okay, I'll change that

**Comment by Mehak-Mattoo** [comment]
Done with the changes 
a1

**Review by Latish705 — APPROVED** [review]

**Pull request merged**
