### PR TITLE
Update responsiveness of Footer

### LINKED ISSUE #3: [Bug]: Need to improve the responsiveness of footer
image

We could improve the responsive design for footer for mobile

### PR DESCRIPTION
**Pull request by shivamnarkar47**
### Description

Added the Footer which was displayed in flex-col into flex-row and also changed the position of Social Media Icons below the Navigation in mobile version

### Fixes
Fixes #3 issue

### Type of PR

- [x]  Bug fix
- [ ] Feature enhancement
- [ ] Documentation update
- [ ] Refactoring
- [ ] Other (specify): _______________

### Summary

ChatGPT
The task involved reorganizing the layout of a webpage. Specifically, the footer, initially displayed in a column layout, was converted to a row layout. Additionally, the position of social media icons was adjusted to appear below the navigation bar in the mobile version of the website.

### Screenshots (if applicable)
- Before : 
image
-  After : 
image

### Additional Notes

[Include any additional information or context that might be helpful for reviewers.]

### Checklist

- [x] I have read and followed the [Pull Requests and Issues guidelines](https://github.com/digitomize/digitomize/blob/main/PR_GUIDELINES.md#pull-requests-and-issues).
- [x] The code has been properly linted and formatted using `npm run lint:fix` and `npm run format:fix`.
- [x] I have tested the changes thoroughly before submitting this pull request.
- [x] I have provided relevant issue numbers, snapshots, and videos after making the changes.
- [x] I have not borrowed code without disclosing it, if applicable.
- [x] This pull request is not a Work In Progress (WIP), and only completed and tested changes are included.
- [x] I have tested these changes locally.
- [x] My code follows the project's style guidelines.
- [x] I have updated the documentation accordingly.
- [x] This PR has a corresponding issue in the issue tracker.

## Summary by CodeRabbit

- **Style**
	- Adjusted the positioning of a link element in the app for better alignment across different screen sizes.
	- Updated footer layout for improved spacing, alignment, and responsiveness.
	- Enhanced visibility and positioning of social media icons based on screen size.

### CODE REVIEW

**Comment by Latish705** [comment]
@shivamnarkar47 can you show web view

**Comment by shivamnarkar47** [comment]
> @shivamnarkar47 can you show web view

The web view is untouched only the mobile view has been fixed.

**Review by Latish705 — APPROVED** [review]
need to show web view to show that it doesn't change and is consistent

**Comment by Latish705** [comment]
> need to show web view to show that it doesn't change and is consistent

@shivamnarkar47

**Pull request merged**
